# Generated by Django 5.2.7 on 2025-12-07 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('motoristas', '0001_initial'),
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.IntegerField(blank=True, null=True)),
                ('destino', models.CharField(max_length=255)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('previsao_retorno', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('AGUARDANDO_SAIDA', 'Aguardando Saída'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_reprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato')),
                ('gestor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='motoristas.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='veiculos.veiculo')),
            ],
        ),
    ]
