# Generated by Django 6.0.3 on 2026-04-02 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('motoristas', '0001_initial'),
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_nome', models.CharField(blank=True, max_length=120, null=True)),
                ('id_contrato', models.IntegerField(blank=True, null=True)),
                ('tag_interna', models.CharField(blank=True, db_index=True, help_text='Código identificador interno da solicitação (ex: VA-950, TAG-123)', max_length=50, null=True)),
                ('destino', models.CharField(max_length=255)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('previsao_retorno', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_CHECKLIST', 'Aguardando Checklist'), ('AGUARDANDO_SAIDA_PORTARIA', 'Aguardando Saída na Portaria'), ('EM_TRANSITO', 'Em Trânsito'), ('REPROVADA', 'Reprovada'), ('CANCELADA', 'Cancelada'), ('AGUARDANDO_CHECKLIST_RETORNO', 'Aguardando Checklist Retorno'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=40)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_reprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('cancelado_por_nome', models.CharField(blank=True, max_length=120, null=True)),
                ('origem', models.CharField(choices=[('SISTEMA', 'Gerada pelo sistema'), ('MANUAL', 'Criada manualmente')], db_index=True, default='SISTEMA', max_length=20)),
                ('gestor_responsavel_nome', models.CharField(blank=True, max_length=120, null=True)),
                ('observacao_aprovacao', models.TextField(blank=True, help_text='Observações do gestor ao aprovar a solicitação', null=True)),
                ('gestor_reprovador_nome', models.CharField(blank=True, max_length=120, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True, help_text='Motivo informado pelo gestor ao reprovar a solicitação', null=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_canceladas', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato')),
                ('gestor_reprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_reprovadas', to=settings.AUTH_USER_MODEL)),
                ('gestor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='motoristas.motorista')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='veiculos.veiculo')),
            ],
        ),
    ]
