# Generated by Django 5.2.7 on 2025-12-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_alter_solicitacaoveiculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoveiculo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_CHECKLIST_SAIDA', 'Aguardando checklist de saída'), ('AGUARDANDO_SAIDA_PORTARIA', 'Aguardando saída na portaria'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_CHECKLIST_RETORNO', 'Aguardando checklist de retorno'), ('FINALIZADA', 'Finalizada'), ('REPROVADA', 'Reprovada')], default='PENDENTE', max_length=40),
        ),
    ]
