# Generated by Django 5.2.7 on 2025-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_alter_solicitacaoveiculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoveiculo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('AGUARDANDO_CHECKLIST', 'Aguardando Checklist'), ('AGUARDANDO_SAIDA_PORTARIA', 'Aguardando Saída na Portaria'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_CHECKLIST_RETORNO', 'Aguardando Checklist de Retorno'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=40),
        ),
    ]
