# Generated by Django 5.2.7 on 2025-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_alter_solicitacaoveiculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoveiculo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_CHECKLIST', 'Aguardando Checklist'), ('AGUARDANDO_SAIDA_PORTARIA', 'Aguardando Saída na Portaria'), ('EM_TRANSITO', 'Em Trânsito'), ('AGUARDANDO_CHECKLIST_RETORNO', 'Aguardando Checklist Retorno'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=40),
        ),
    ]
