# Generated by Django 5.2.7 on 2025-12-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_alter_solicitacaoveiculo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='gestor_responsavel_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
