# Generated by Django 5.2.7 on 2025-12-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_solicitacaoveiculo_gestor_responsavel_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='gestor_reprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_reprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='gestor_reprovador_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoveiculo',
            name='gestor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
