# Generated by Django 5.2.7 on 2025-12-14 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0009_solicitacaoveiculo_solicitante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='porteiro_retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_retorno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='porteiro_retorno_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='porteiro_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='porteiro_saida_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
