# Generated by Django 5.2.7 on 2025-12-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0010_solicitacaoveiculo_porteiro_retorno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoveiculo',
            name='porteiro_retorno',
        ),
        migrations.RemoveField(
            model_name='solicitacaoveiculo',
            name='porteiro_retorno_nome',
        ),
        migrations.RemoveField(
            model_name='solicitacaoveiculo',
            name='porteiro_saida',
        ),
        migrations.RemoveField(
            model_name='solicitacaoveiculo',
            name='porteiro_saida_nome',
        ),
    ]
