# Generated by Django 5.2.7 on 2025-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0011_remove_solicitacaoveiculo_porteiro_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Gerada pelo sistema'), ('MANUAL', 'Criada manualmente')], db_index=True, default='SISTEMA', max_length=20),
        ),
    ]
