# Generated by Django 5.2.7 on 2026-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0012_solicitacaoveiculo_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='motivo_reprovacao',
            field=models.TextField(blank=True, help_text='Motivo informado pelo gestor ao reprovar a solicitação', null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='observacao_aprovacao',
            field=models.TextField(blank=True, help_text='Observações do gestor ao aprovar a solicitação', null=True),
        ),
    ]
