# Generated by Django 5.2.7 on 2026-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0013_solicitacaoveiculo_motivo_reprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
