# Generated by Django 5.2.7 on 2026-02-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0014_solicitacaoveiculo_data_cancelamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='cancelado_por_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoveiculo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_CHECKLIST', 'Aguardando Checklist'), ('AGUARDANDO_SAIDA_PORTARIA', 'Aguardando Saída na Portaria'), ('EM_TRANSITO', 'Em Trânsito'), ('REPROVADA', 'Reprovada'), ('CANCELADA', 'Cancelada'), ('AGUARDANDO_CHECKLIST_RETORNO', 'Aguardando Checklist Retorno'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=40),
        ),
    ]
