# Generated by Django 5.2.7 on 2026-03-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0015_solicitacaoveiculo_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoveiculo',
            name='tag_interna',
            field=models.CharField(blank=True, db_index=True, help_text='Código identificador interno da solicitação (ex: VA-950, TAG-123)', max_length=50, null=True),
        ),
    ]
