# Generated by Django 5.2.7 on 2025-12-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('motoristas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_saida', models.BigIntegerField(blank=True, null=True)),
                ('km_retorno', models.BigIntegerField(blank=True, null=True)),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('destino', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('distancia_percorrida', models.BigIntegerField(blank=True, null=True)),
                ('finalidade', models.CharField(blank=True, max_length=255)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoristas.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
        ),
    ]
