# Generated by Django 6.0.3 on 2026-04-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='foto_saida_avaria',
            field=models.ImageField(blank=True, null=True, upload_to='terceiros/saida/avarias/%Y/%m/%d/', verbose_name='Foto de avaria (saída)'),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='foto_saida_extra',
            field=models.ImageField(blank=True, null=True, upload_to='terceiros/saida/extra/%Y/%m/%d/', verbose_name='Foto extra (saída)'),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='foto_saida_veiculo',
            field=models.ImageField(blank=True, null=True, upload_to='terceiros/saida/veiculo/%Y/%m/%d/', verbose_name='Foto do veículo (saída)'),
        ),
    ]
