# Generated by Django 5.2.7 on 2025-12-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='solicitacoes.solicitacaoveiculo'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em Trânsito'), ('finalizado', 'Finalizado')], default='aberto', max_length=20),
        ),
    ]
