# Generated by Django 5.2.7 on 2025-12-07 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_movimentacao_solicitacao_movimentacao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em Trânsito'), ('finalizado', 'Finalizado'), ('divergencia_km', 'Divergência de KM')], default='aberto', max_length=20),
        ),
        migrations.CreateModel(
            name='ChecklistRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_motorista', models.IntegerField()),
                ('combustivel_motorista', models.IntegerField()),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_traseira', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_lado_esq', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_lado_dir', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('avarias', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_retorno', to='movimentacoes.movimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenciaRetornoPortaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_portaria', models.IntegerField()),
                ('observacao_portaria', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retorno_portaria', to='movimentacoes.movimentacao')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
