# Generated by Django 6.0.3 on 2026-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_movimentacaoterceiro_foto_saida_avaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='foto_material',
            field=models.ImageField(blank=True, null=True, upload_to='terceiros/material/%Y/%m/%d/', verbose_name='Foto do material/equipamento'),
        ),
    ]
