# Generated by Django 5.2.7 on 2025-12-07 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_alter_movimentacao_status_checklistretorno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistretorno',
            name='avarias',
        ),
        migrations.RemoveField(
            model_name='checklistretorno',
            name='combustivel_motorista',
        ),
        migrations.RemoveField(
            model_name='checklistretorno',
            name='km_motorista',
        ),
        migrations.AddField(
            model_name='checklistretorno',
            name='avarias_novas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistretorno',
            name='luzes_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checklistretorno',
            name='pneus_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('aguardando_checklist_saida', 'Aguardando Checklist de Saída'), ('aguardando_saida_portaria', 'Aguardando Saída da Portaria'), ('em_andamento', 'Em Andamento'), ('aguardando_checklist_retorno', 'Aguardando Checklist de Retorno'), ('aguardando_retorno_portaria', 'Aguardando Retorno da Portaria'), ('divergencia_km', 'Divergência de KM'), ('finalizado', 'Finalizado')], max_length=40),
        ),
        migrations.CreateModel(
            name='ChecklistSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pneus_ok', models.BooleanField(default=True)),
                ('luzes_ok', models.BooleanField(default=True)),
                ('documentos_ok', models.BooleanField(default=True)),
                ('equipamentos_ok', models.BooleanField(default=True)),
                ('avarias', models.TextField(blank=True, null=True)),
                ('foto_painel', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_traseira', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_lado_esq', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('foto_lado_dir', models.ImageField(blank=True, null=True, upload_to='checklists/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_saida', to='movimentacoes.movimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='RetornoPortaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_retorno', models.IntegerField()),
                ('combustivel_retorno', models.IntegerField(blank=True, null=True)),
                ('observacao_portaria', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retorno_portaria', to='movimentacoes.movimentacao')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConferenciaRetornoPortaria',
        ),
    ]
