# Generated by Django 6.0.3 on 2026-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_movimentacaoterceiro_foto_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='descricao_material',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do material/equipamento'),
        ),
    ]
