# Generated by Django 5.2.7 on 2025-12-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_remove_checklistretorno_avarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistretorno',
            name='data_checklist',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistretorno',
            name='foto_painel',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/retorno/'),
        ),
        migrations.AlterField(
            model_name='checklistretorno',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/retorno/'),
        ),
        migrations.AlterField(
            model_name='checklistretorno',
            name='foto_lado_dir',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/retorno/'),
        ),
        migrations.AlterField(
            model_name='checklistretorno',
            name='foto_lado_esq',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/retorno/'),
        ),
        migrations.AlterField(
            model_name='checklistretorno',
            name='foto_traseira',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/retorno/'),
        ),
    ]
