# Generated by Django 5.2.7 on 2025-12-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_checklistretorno_data_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistretorno',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistretorno',
            name='foto_check_ret',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/'),
        ),
        migrations.AddField(
            model_name='checklistretorno',
            name='porteiro_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistretorno',
            name='porteiro_saida_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='checklistsaida',
            name='foto_check_saida',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/'),
        ),
    ]
