# Generated by Django 5.2.7 on 2025-12-15 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0006_checklistretorno_data_saida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='solicitacao',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='porteiro_retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_porteiro_retorno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='porteiro_retorno_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='porteiro_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_porteiro_saida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='porteiro_saida_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
