# Generated by Django 5.2.7 on 2025-12-15 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0007_remove_movimentacao_contrato_and_more'),
        ('solicitacoes', '0011_remove_solicitacaoveiculo_porteiro_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='solicitacoes.solicitacaoveiculo'),
        ),
    ]
