# Generated by Django 5.2.7 on 2025-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0008_movimentacao_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Gerada pelo sistema'), ('MANUAL', 'Criada manualmente')], default='SISTEMA', max_length=20),
        ),
    ]
