# Generated by Django 5.2.7 on 2025-12-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0009_movimentacao_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='origem',
            field=models.CharField(choices=[('SISTEMA', 'Gerada pelo sistema'), ('MANUAL', 'Criada manualmente')], db_index=True, default='SISTEMA', max_length=20),
        ),
    ]
