# Generated by Django 5.2.7 on 2025-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0010_alter_movimentacao_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='cacamba_descricao',
            field=models.TextField(blank=True, help_text='Descreva o material transportado na caçamba', null=True, verbose_name='Descrição do material na caçamba'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='com_cacamba',
            field=models.BooleanField(default=False, help_text='Marque se o veículo saiu com caçamba carregada', verbose_name='Veículo com caçamba'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='com_prancha',
            field=models.BooleanField(default=False, help_text='Marque se o veículo saiu com máquina na prancha', verbose_name='Veículo com prancha'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_portaria_avaria',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/', verbose_name='Foto de avaria (portaria)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_portaria_equipamento',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/equipamento/', verbose_name='Foto do equipamento (caçamba/prancha)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_portaria_geral',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/', verbose_name='Foto geral do veículo (portaria)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_portaria_painel',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/', verbose_name='Foto do painel (portaria)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='observacao_portaria',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da portaria (saída)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='prancha_descricao',
            field=models.TextField(blank=True, help_text='Descreva a máquina transportada na prancha', null=True, verbose_name='Descrição da máquina na prancha'),
        ),
    ]
