# Generated by Django 5.2.7 on 2025-12-22 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('movimentacoes', '0011_movimentacao_cacamba_descricao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('descricao_veiculo', models.CharField(help_text='Ex: Caminhão Volvo / Empresa XYZ', max_length=150)),
                ('empresa', models.CharField(max_length=120)),
                ('motorista_nome', models.CharField(max_length=120)),
                ('documento_motorista', models.CharField(blank=True, max_length=30, null=True)),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DENTRO', 'Dentro da empresa'), ('SAIU', 'Saiu da empresa')], default='DENTRO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.contrato')),
                ('porteiro_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceiro_entrada', to=settings.AUTH_USER_MODEL)),
                ('porteiro_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceiro_saida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
    ]
