# Generated by Django 5.2.7 on 2025-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0012_movimentacaoterceiro'),
    ]



    operations = [
        migrations.AlterField(
            model_name='movimentacaoterceiro',
            name='status',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], default='ENTRADA', max_length=20),
        ),
    ]
