# Generated by Django 5.2.7 on 2025-12-23 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0013_alter_movimentacaoterceiro_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoterceiro',
            options={},
        ),
        migrations.RemoveField(
            model_name='movimentacaoterceiro',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='movimentacaoterceiro',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='movimentacaoterceiro',
            name='descricao_veiculo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoterceiro',
            name='documento_motorista',
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='foto_motorista',
            field=models.ImageField(blank=True, null=True, upload_to='terceiros/motorista/'),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='foto_placa',
            field=models.ImageField(default='', upload_to='terceiros/placa/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='foto_veiculo',
            field=models.ImageField(blank=True, null=True, upload_to='terceiros/veiculo/'),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='porteiro_entrada_nome',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='porteiro_saida_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='tipo_veiculo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaoterceiro',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoterceiro',
            name='porteiro_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceiros_entrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaoterceiro',
            name='porteiro_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceiros_saida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaoterceiro',
            name='status',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], default='ENTRADA', max_length=10),
        ),
    ]
