# Generated by Django 5.2.7 on 2025-12-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0014_alter_movimentacaoterceiro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='descricao_veiculo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição do veículo'),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='tags',
            field=models.CharField(blank=True, help_text='Ex: MANUTENCAO, VISITA, DESCARGA', max_length=120),
        ),
    ]
