# Generated by Django 5.2.7 on 2026-01-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0015_movimentacaoterceiro_descricao_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='bservacoes_entrada',
            field=models.TextField(blank=True, help_text='Observações feitas pelo porteiro no momento da entrada', null=True, verbose_name='Observações da entrada'),
        ),
    ]
