# Generated by Django 5.2.7 on 2026-01-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0016_movimentacaoterceiro_bservacoes_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoterceiro',
            name='bservacoes_entrada',
        ),
        migrations.RemoveField(
            model_name='movimentacaoterceiro',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoterceiro',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='motivo_entrada',
            field=models.TextField(default='', verbose_name='Motivo da entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='observacoes_entrada',
            field=models.TextField(blank=True, help_text='Observações feitas pelo porteiro no momento da entrada', verbose_name='Observações da entrada'),
        ),
        migrations.AddField(
            model_name='movimentacaoterceiro',
            name='observacoes_saida',
            field=models.TextField(blank=True, help_text='Observações feitas pelo porteiro no momento da saída', verbose_name='Observações da saída'),
        ),
    ]
