# Generated by Django 5.2.7 on 2026-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0017_remove_movimentacaoterceiro_bservacoes_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_avaria',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/', verbose_name='Foto de avaria (retorno)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_cacamba',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/cacamba/', verbose_name='Foto da caçamba (retorno)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_equipamento',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/equipamento/', verbose_name='Foto do equipamento (retorno)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_geral',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/', verbose_name='Foto geral do veículo (retorno)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_painel',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/', verbose_name='Foto do painel (retorno)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_porta_malas',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/porta_malas/', verbose_name='Foto do porta-malas (retorno)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_prancha',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/prancha/', verbose_name='Foto da prancha (retorno)'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='fotos_retorno',
            field=models.JSONField(blank=True, help_text='Armazena informações das fotos do retorno em formato JSON', null=True, verbose_name='Lista de fotos do retorno'),
        ),
    ]
