# Generated by Django 5.2.7 on 2026-01-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('movimentacoes', '0018_movimentacao_foto_retorno_avaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_saida'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato', verbose_name='Contrato vinculado'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_avaria',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/', verbose_name='Foto de avaria (portaria saída)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_equipamento',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/equipamento/', verbose_name='Foto do equipamento (caçamba/prancha) saída'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_geral',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/', verbose_name='Foto geral do veículo (portaria saída)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_painel',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/', verbose_name='Foto do painel (portaria saída)'),
        ),
    ]
