# Generated by Django 5.2.7 on 2026-01-05 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('motoristas', '0001_initial'),
        ('movimentacoes', '0019_alter_movimentacao_options_movimentacao_contrato_and_more'),
        ('solicitacoes', '0012_solicitacaoveiculo_origem'),
        ('veiculos', '0004_alter_veiculo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='fotos_retorno',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='foto_retorno_combustivel',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/combustivel/%Y/%m/%d/', verbose_name='Foto do marcador de combustível (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='cacamba_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do material na caçamba'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_avaria',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/avarias/%Y/%m/%d/', verbose_name='Foto de avarias (saída)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_equipamento',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/equipamento/%Y/%m/%d/', verbose_name='Foto do equipamento (saída)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_geral',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/geral/%Y/%m/%d/', verbose_name='Foto geral do veículo (saída)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_portaria_painel',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/saida/painel/%Y/%m/%d/', verbose_name='Foto do painel/odômetro (saída)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_retorno_avaria',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/avarias/%Y/%m/%d/', verbose_name='Foto de avarias (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_retorno_cacamba',
            field=models.ImageField(blank=True, help_text='Foto da caçamba no retorno', null=True, upload_to='portaria/retorno/cacamba/%Y/%m/%d/', verbose_name='Foto da caçamba (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_retorno_equipamento',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/equipamento/%Y/%m/%d/', verbose_name='Foto do equipamento (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_retorno_geral',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/geral/%Y/%m/%d/', verbose_name='Foto geral do veículo (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_retorno_painel',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/retorno/painel/%Y/%m/%d/', verbose_name='Foto do painel/odômetro (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_retorno_porta_malas',
            field=models.ImageField(blank=True, help_text='Foto do porta-malas no retorno', null=True, upload_to='portaria/retorno/porta_malas/%Y/%m/%d/', verbose_name='Foto do porta-malas (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='foto_retorno_prancha',
            field=models.ImageField(blank=True, help_text='Foto da máquina na prancha no retorno', null=True, upload_to='portaria/retorno/prancha/%Y/%m/%d/', verbose_name='Foto da prancha (retorno)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='prancha_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da máquina na prancha'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['status', 'data_saida'], name='movimentaco_status_e7dde5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['veiculo', 'data_saida'], name='movimentaco_veiculo_5ef1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['motorista', 'data_saida'], name='movimentaco_motoris_767284_idx'),
        ),
    ]
