# Generated by Django 5.2.7 on 2026-01-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0020_remove_movimentacao_fotos_retorno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistretorno',
            options={'verbose_name': 'Checklist de Retorno', 'verbose_name_plural': 'Checklists de Retorno'},
        ),
        migrations.AlterModelOptions(
            name='checklistsaida',
            options={'verbose_name': 'Checklist de Saída', 'verbose_name_plural': 'Checklists de Saída'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoterceiro',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'Movimentação de Terceiro', 'verbose_name_plural': 'Movimentações de Terceiros'},
        ),
        migrations.AlterModelOptions(
            name='retornoportaria',
            options={'verbose_name': 'Retorno da Portaria', 'verbose_name_plural': 'Retornos da Portaria'},
        ),
    ]
