# Generated by Django 5.2.7 on 2026-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0021_alter_checklistretorno_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='observacao_portaria_retorno',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da portaria (retorno)'),
        ),
    ]
