# Generated by Django 5.2.7 on 2025-12-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
