# Generated by Django 5.2.7 on 2025-12-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_perfilusuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
