# Generated by Django 5.2.7 on 2025-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_perfilusuario_nome_exibicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome exibido'),
        ),
    ]
