# Generated by Django 5.2.7 on 2025-12-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_perfilusuario_nome_exibicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gestor', 'Gestor'), ('portaria', 'Portaria'), ('basico', 'Solicitante')], default='basico', max_length=20),
        ),
    ]
