# Generated by Django 5.2.7 on 2025-12-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('renavam', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('tag_interna', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Utilitario', 'Utilitário'), ('Caminhao', 'Caminhão')], max_length=20)),
                ('categoria', models.CharField(choices=[('Leve', 'Leve'), ('Pesado', 'Pesado'), ('Passageiro', 'Passageiro'), ('Carga', 'Carga'), ('Onibus', 'Ônibus')], max_length=20)),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Diesel', 'Diesel'), ('Flex', 'Flex'), ('GNV', 'GNV'), ('Elétrico', 'Elétrico'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('km_atual', models.IntegerField(default=0)),
                ('tipo_propriedade', models.CharField(choices=[('Proprio', 'Próprio'), ('Locado', 'Locado')], default='Proprio', max_length=20)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('EmTransito', 'Em Trânsito'), ('Manutencao', 'Manutenção'), ('Reservado', 'Reservado')], default='Disponivel', max_length=20)),
                ('ipva_vencimento', models.DateField(blank=True, null=True)),
                ('licenciamento_vencimento', models.DateField(blank=True, null=True)),
                ('seguro', models.BooleanField(default=False)),
                ('seguro_validade', models.DateField(blank=True, null=True)),
                ('apolice_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato')),
            ],
        ),
    ]
