# Generated by Django 6.0.3 on 2026-04-02 22:11

import django.core.validators
import django.db.models.deletion
import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, validators=[veiculos.models.validar_placa_modelo])),
                ('renavam', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Renavam deve conter apenas números', regex='^\\d+$')])),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('tag_interna', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tag_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('Carro', 'Carro'), ('Caminhao', 'Caminhão'), ('Utilitario', 'Utilitário'), ('Equipamento', 'Equipamento'), ('Implemento', 'Implemento'), ('Veiculo', 'Veículo'), ('Veiculos', 'Veículos'), ('Van', 'Van'), ('Onibus', 'Ônibus'), ('Reboque', 'Reboque'), ('Caminhonete', 'Caminhonete')], max_length=50)),
                ('categoria', models.CharField(choices=[('Leve', 'Leve'), ('Medio', 'Médio'), ('Pesado', 'Pesado'), ('Equipamento', 'Equipamento'), ('Implemento', 'Implemento'), ('VAN', 'VAN'), ('Micro-Ônibus', 'Micro-Ônibus'), ('Caminhão Basculante', 'Caminhão Basculante'), ('Caminhão de Transporte', 'Caminhão de Transporte'), ('Caminhão Pipa', 'Caminhão Pipa'), ('Caminhão Lubrificante', 'Caminhão Lubrificante'), ('Veículo de Apoio', 'Veículo de Apoio'), ('Grupo Gerador', 'Grupo Gerador'), ('Escavadeira Hidráulica', 'Escavadeira Hidráulica'), ('Pá Mecânica', 'Pá Mecânica'), ('Outros', 'Outros')], max_length=100)),
                ('combustivel', models.CharField(choices=[('Flex', 'Flex'), ('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Etanol', 'Etanol'), ('Eletrico', 'Elétrico'), ('N/A', 'N/A'), ('Alcool/Gasolina', 'Álcool/Gasolina')], max_length=50)),
                ('km_atual', models.PositiveIntegerField(default=0)),
                ('km_anterior', models.PositiveIntegerField(default=0)),
                ('tipo_propriedade', models.CharField(choices=[('Proprio', 'Próprio'), ('Locado', 'Locado'), ('Comodato', 'Comodato'), ('Arrendado', 'Arrendado'), ('LOCADO', 'LOCADO')], default='Proprio', max_length=40)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('EmTransito', 'Em Trânsito'), ('Manutencao', 'Manutenção'), ('Reservado', 'Reservado')], default='Disponivel', max_length=40)),
                ('ipva_vencimento', models.DateField(blank=True, null=True)),
                ('licenciamento_vencimento', models.DateField(blank=True, null=True)),
                ('seguro', models.BooleanField(default=False)),
                ('seguro_validade', models.DateField(blank=True, null=True)),
                ('apolice_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('origem', models.CharField(blank=True, choices=[('MANUAL', 'Cadastro Manual'), ('PROTHEUS', 'Importado do Protheus'), ('IMPORTACAO', 'Importação por Planilha')], default='MANUAL', max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato')),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_anterior', models.PositiveIntegerField()),
                ('km_novo', models.PositiveIntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('RETORNO_PORTARIA', 'Retorno Portaria'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('IMPORTACAO', 'Importação de Dados')], max_length=50)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_km', to='veiculos.veiculo')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('placa',), name='unique_veiculo_placa'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('renavam',), name='unique_veiculo_renavam'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('tag_interna',), name='unique_veiculo_tag_interna'),
        ),
    ]
