# Generated by Django 5.2.7 on 2025-12-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='km_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='km_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HistoricoKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_anterior', models.PositiveIntegerField()),
                ('km_novo', models.PositiveIntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('RETORNO_PORTARIA', 'Retorno Portaria'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('IMPORTACAO', 'Importação de Dados')], max_length=50)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_km', to='veiculos.veiculo')),
            ],
        ),
    ]
