# Generated by Django 5.2.7 on 2025-12-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_km_anterior_alter_veiculo_km_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponível'), ('EmTransito', 'Em Trânsito'), ('Manutencao', 'Manutenção'), ('Reservado', 'Reservado'), ('Em_Andamento', 'Em_Andamento')], default='Disponivel', max_length=40),
        ),
    ]
