# Generated by Django 6.0.3 on 2026-04-03 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('veiculos', '0002_alter_veiculo_categoria'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='veiculo',
            name='unique_veiculo_placa',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cod_interno',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('placa', 'tipo'), name='unique_placa_por_tipo'),
        ),
    ]
