# Generated by Django 5.2.7 on 2025-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_alter_veiculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponível'), ('EmTransito', 'Em Trânsito'), ('Manutencao', 'Manutenção'), ('Reservado', 'Reservado')], default='Disponivel', max_length=40),
        ),
    ]
