# Generated by Django 6.0.3 on 2026-04-03 03:24

import django.core.validators
import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('veiculos', '0003_remove_veiculo_unique_veiculo_placa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='veiculo',
            name='unique_placa_por_tipo',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('Leve', 'Leve'), ('Medio', 'Médio'), ('Pesado', 'Pesado'), ('Equipamento', 'Equipamento'), ('Implemento', 'Implemento'), ('VAN', 'VAN'), ('Micro-Ônibus', 'Micro-Ônibus'), ('Caminhão Basculante', 'Caminhão Basculante'), ('Caminhão de Transporte', 'Caminhão de Transporte'), ('Caminhão Pipa', 'Caminhão Pipa'), ('Caminhão Lubrificante', 'Caminhão Lubrificante'), ('Veículo de Apoio', 'Veículo de Apoio'), ('Grupo Gerador', 'Grupo Gerador'), ('Escavadeira Hidráulica', 'Escavadeira Hidráulica'), ('Pá Mecânica', 'Pá Mecânica'), ('Outros', 'Outros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, validators=[veiculos.models.validar_placa_modelo]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Renavam deve conter apenas números', regex='^\\d+$')]),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('placa',), name='unique_veiculo_placa'),
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cod_interno',
        ),
    ]
