# Generated by Django 6.0.3 on 2026-04-06 13:01

import django.core.validators
import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_remove_veiculo_unique_placa_por_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='veiculo',
            name='unique_veiculo_renavam',
        ),
        migrations.RemoveConstraint(
            model_name='veiculo',
            name='unique_veiculo_placa',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[veiculos.models.validar_placa_modelo]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Renavam deve conter apenas números', regex='^\\d+$')]),
        ),
    ]
