# Generated by Django 5.2.7 on 2026-03-24 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('veiculos', '0004_alter_veiculo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicokm',
            options={'ordering': ['-data_registro']},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa']},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='origem',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Cadastro Manual'), ('PROTHEUS', 'Importado do Protheus'), ('IMPORTACAO', 'Importação por Planilha')], default='MANUAL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Placa deve estar no formato ABC-1234 (3 letras, hífen, 4 números)', regex='^[A-Z]{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Renavam deve conter apenas números', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tag_interna',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('placa',), name='unique_veiculo_placa'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('renavam',), name='unique_veiculo_renavam'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('tag_interna',), name='unique_veiculo_tag_interna'),
        ),
    ]
