# Generated by Django 6.0.3 on 2026-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_remove_veiculo_unique_veiculo_renavam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='identificador_externo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
