# Generated by Django 5.2.7 on 2026-03-25 11:15

import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_historicokm_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, validators=[veiculos.models.validar_placa_modelo]),
        ),
    ]
