# Generated by Django 6.0.3 on 2026-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0006_veiculo_identificador_externo_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='horimetro_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='horimetro_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
