# Generated by Django 6.0.3 on 2026-04-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0007_veiculo_horimetro_anterior_veiculo_horimetro_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('Leve', 'Leve'), ('Medio', 'Médio'), ('Pesado', 'Pesado'), ('Equipamento', 'Equipamento'), ('Implemento', 'Implemento'), ('VAN', 'VAN'), ('Micro-Ônibus', 'Micro-Ônibus'), ('Onibus', 'Ônibus'), ('Caminhão Basculante', 'Caminhão Basculante'), ('Caminhão de Transporte', 'Caminhão de Transporte'), ('Caminhão Pipa', 'Caminhão Pipa'), ('Caminhão Lubrificante', 'Caminhão Lubrificante'), ('Veículo de Apoio', 'Veículo de Apoio'), ('Grupo Gerador', 'Grupo Gerador'), ('Escavadeira Hidráulica', 'Escavadeira Hidráulica'), ('Pá Mecânica', 'Pá Mecânica'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
