# Generated by Django 6.0.3 on 2026-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0010_alter_veiculo_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('Flex', 'Flex'), ('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Diesel S10', 'Diesel S10'), ('Etanol', 'Etanol'), ('Eletrico', 'Elétrico'), ('Hibrido', 'Híbrido'), ('N/A', 'N/A'), ('Alcool/Gasolina', 'Álcool/Gasolina')], max_length=50),
        ),
    ]
