# Generated by Django 6.0.3 on 2026-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0013_alter_veiculo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('Leve', 'Leve'), ('Medio', 'Médio'), ('Pesado', 'Pesado'), ('Equipamento', 'Equipamento'), ('Implemento', 'Implemento'), ('VAN', 'VAN'), ('Agricola', 'Agrícola'), ('Micro-Ônibus', 'Micro-Ônibus'), ('Onibus', 'Ônibus'), ('Caminhão Basculante', 'Caminhão Basculante'), ('Caminhão de Transporte', 'Caminhão de Transporte'), ('Caminhão Pipa', 'Caminhão Pipa'), ('Caminhão Lubrificante', 'Caminhão Lubrificante'), ('Caminhonete', 'Caminhonete'), ('Caminhão Comboio', 'Caminhão Comboio'), ('Caminhao Madeireiro', 'Caminhão Madeireiro'), ('Caminhão Munk', 'Caminhão Munk'), ('Trator de Esteira', 'Trator de Esteira'), ('Prancha', 'Prancha'), ('Rolo Compressor', 'Rolo Compressor'), ('Rolo Compactador', 'Rolo Compactador'), ('Veículo de Apoio', 'Veículo de Apoio'), ('Reboque', 'Reboque'), ('Carreta', 'Carreta'), ('Grupo Gerador', 'Grupo Gerador'), ('Escavadeira Hidráulica', 'Escavadeira Hidráulica'), ('Escavadeira Anfíbia', 'Escavadeira Anfíbia'), ('Motoniveladora', 'Motoniveladora'), ('Pá Mecânica', 'Pá Mecânica'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
