# Generated by Django 6.0.3 on 2026-04-02 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cnh_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cnh_categoria', models.CharField(blank=True, max_length=3, null=True)),
                ('cnh_vencimento', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('origem', models.CharField(blank=True, choices=[('MANUAL', 'Cadastro Manual'), ('PROTHEUS', 'Importado do Protheus'), ('IMPORTACAO', 'Importação por Planilha')], default='MANUAL', max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('cpf',), name='unique_motorista_cpf'), models.UniqueConstraint(fields=('matricula',), name='unique_motorista_matricula')],
            },
        ),
    ]
