# Generated by Django 5.2.7 on 2026-03-24 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('motoristas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='motorista',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='origem',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Cadastro Manual'), ('PROTHEUS', 'Importado do Protheus'), ('IMPORTACAO', 'Importação por Planilha')], default='MANUAL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='motorista',
            constraint=models.UniqueConstraint(fields=('cpf',), name='unique_motorista_cpf'),
        ),
        migrations.AddConstraint(
            model_name='motorista',
            constraint=models.UniqueConstraint(fields=('matricula',), name='unique_motorista_matricula'),
        ),
    ]
