# Generated by Django 6.0.3 on 2026-04-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
